/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.JOptionPane;
import rojerusan.RSNotifyAnimated;

/**
 *
 * @author sis.informacion01
 */
public class GestionProcesos extends javax.swing.JDialog {

    /**
     * Creates new form GestionProcesos
     */
    private int area;
    private int idProceso;
    private Procesos_Condicion parentt; 
    // ...
    public GestionProcesos(java.awt.Frame parent, boolean modal, int idProceso, int area, String nombreProceso, Procesos_Condicion parentt) {
        super(parent, modal);
        initComponents();
        esconderBoton(idProceso);
        this.area= area;
        this.idProceso=idProceso;
        this.parentt = parentt;
        jTNombreProceso.setText(nombreProceso);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jTNombreProceso = new elaprendiz.gui.textField.TextFieldRoundBackground();
        jLabel6 = new javax.swing.JLabel();
        btnGuardar2 = new javax.swing.JButton();
        btnUpdate2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión Procesos");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTNombreProceso.setColorDeBorde(new java.awt.Color(204, 204, 204));
        jTNombreProceso.setColorDeTextoBackground(new java.awt.Color(255, 255, 255));
        jTNombreProceso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTNombreProceso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTNombreProcesoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNombreProcesoKeyTyped(evt);
            }
        });
        jPanel7.add(jTNombreProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 248, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(128, 128, 131));
        jLabel6.setText("Nombre Proceso:");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 134, -1));

        btnGuardar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save_proyect.png"))); // NOI18N
        btnGuardar2.setBorderPainted(false);
        btnGuardar2.setContentAreaFilled(false);
        btnGuardar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar2.setFocusPainted(false);
        btnGuardar2.setFocusable(false);
        btnGuardar2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save_roll.png"))); // NOI18N
        btnGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar2ActionPerformed(evt);
            }
        });
        jPanel7.add(btnGuardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 36, -1));

        btnUpdate2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        btnUpdate2.setBorderPainted(false);
        btnUpdate2.setContentAreaFilled(false);
        btnUpdate2.setFocusPainted(false);
        btnUpdate2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update1.png"))); // NOI18N
        btnUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate2ActionPerformed(evt);
            }
        });
        jPanel7.add(btnUpdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 42, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNombreProcesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreProcesoKeyTyped
        char cara = evt.getKeyChar();
        if (Character.isDigit(cara) || evt.getKeyChar() == '|') {
            evt.consume();
        }
    }//GEN-LAST:event_jTNombreProcesoKeyTyped

    private void btnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar2ActionPerformed
        registrarModificarProcesos(0);
    }//GEN-LAST:event_btnGuardar2ActionPerformed

    private void btnUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate2ActionPerformed
        registrarModificarProcesos(idProceso);
    }//GEN-LAST:event_btnUpdate2ActionPerformed

    private void jTNombreProcesoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreProcesoKeyPressed
       if(jTNombreProceso.getText().length() == 30){
           evt.consume();
       }
    }//GEN-LAST:event_jTNombreProcesoKeyPressed

    private void registrarModificarProcesos(int IDProcesos){
        if (JOptionPane.showOptionDialog(null, "¿Seguro deseas" + (IDProcesos==0?"registrar":"actualizar") + " este proceso?",
                "seleccione...", JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE, null,// null para icono por defecto.
                new Object[]{"SI", "NO"}, "SI") == 0) {
                // ...
                Controlador.Condicion_producto ObjGestionProcesos = new Controlador.Condicion_producto();
                boolean respuesta = ObjGestionProcesos.guardarModificarProcesos(IDProcesos, jTNombreProceso.getText(), area);
                    // ...
            if (respuesta) {
                new rojerusan.RSNotifyAnimated("Realizado!", ("El proceso fue " + (IDProcesos == 0 ? "Registrado" : "Actualizado") + " correctamente..."), 6, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.BottomUp, RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
                parentt.consultarProcesosArea();
                this.dispose();
            } else {
                new rojerusan.RSNotifyAnimated("Alerta!", "La acción no se pudo ejecutar correctamente.", 6, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.BottomUp, RSNotifyAnimated.TypeNotify.WARNING).setVisible(true);
            }
        }
    }    
    
    private void esconderBoton(int accion){
        if(accion == 0){// Registrar
            btnGuardar2.setVisible(true);
            btnUpdate2.setVisible(false);
        }else{//Modificar
            btnGuardar2.setVisible(false);
            btnUpdate2.setVisible(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionProcesos dialog = new GestionProcesos(new javax.swing.JFrame(), true, 0, 0, "", null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar2;
    public static javax.swing.JButton btnUpdate2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel7;
    public static elaprendiz.gui.textField.TextFieldRoundBackground jTNombreProceso;
    // End of variables declaration//GEN-END:variables
}
